### ISSUE TITLE
Make sure all Skills from the market can install (dependencies)

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/OpenVoiceOS#19]
### Information
Asd there are no GCC / Compile tools available on MycroftOS, we have to make sure all Skills from the Market can be installed without any problems (unless the skill is very specific for a certain platform, but even then I will try to get it done somehow)

Python3.7 and PIP are installed. PIP should be configured to also look at piwheels (already there). Where possible wheels should be preferred otherwise source should be ok, but sources with gcc (or other compiler) should be wheels only and if that is not be possible be pre-installed and therefor compiled at buildtime of the system.

**Comment by ChanceNCounter** [comment]
Should this be moved to the installer skill?

**Comment by j1nx** [comment]
This can be closed. Had a look at this and included most of the major gcc/python pip packages that might be needed.
